parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:import/recommended
  - plugin:import/typescript
plugins:
  - "unused-imports"
rules:
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-unused-vars": off
  "unused-imports/no-unused-imports": error
  "prefer-const": ["error", { "destructuring": "all" }]
